//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ERPSolution.Areas.Dyeing.Reports.DS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsDyeingReprocessHistory")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsDyeingReprocessHistory : global::System.Data.DataSet {
        
        private dsDyeingReprocessHistoryDataTable tabledsDyeingReprocessHistory;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dsDyeingReprocessHistory() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dsDyeingReprocessHistory(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dsDyeingReprocessHistory"] != null)) {
                    base.Tables.Add(new dsDyeingReprocessHistoryDataTable(ds.Tables["dsDyeingReprocessHistory"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dsDyeingReprocessHistoryDataTable _dsDyeingReprocessHistory {
            get {
                return this.tabledsDyeingReprocessHistory;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsDyeingReprocessHistory cln = ((dsDyeingReprocessHistory)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dsDyeingReprocessHistory"] != null)) {
                    base.Tables.Add(new dsDyeingReprocessHistoryDataTable(ds.Tables["dsDyeingReprocessHistory"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledsDyeingReprocessHistory = ((dsDyeingReprocessHistoryDataTable)(base.Tables["dsDyeingReprocessHistory"]));
            if ((initTable == true)) {
                if ((this.tabledsDyeingReprocessHistory != null)) {
                    this.tabledsDyeingReprocessHistory.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsDyeingReprocessHistory";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsDyeingReprocessHistory.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledsDyeingReprocessHistory = new dsDyeingReprocessHistoryDataTable();
            base.Tables.Add(this.tabledsDyeingReprocessHistory);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerialize_dsDyeingReprocessHistory() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsDyeingReprocessHistory ds = new dsDyeingReprocessHistory();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dsDyeingReprocessHistoryRowChangeEventHandler(object sender, dsDyeingReprocessHistoryRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dsDyeingReprocessHistoryDataTable : global::System.Data.TypedTableBase<dsDyeingReprocessHistoryRow> {
            
            private global::System.Data.DataColumn columnCOMP_NAME_EN;
            
            private global::System.Data.DataColumn columnCOMP_SNAME;
            
            private global::System.Data.DataColumn columnREG_ADD_EN;
            
            private global::System.Data.DataColumn columnDYE_BATCH_NO;
            
            private global::System.Data.DataColumn columnMC_ORDER_NO_LST;
            
            private global::System.Data.DataColumn columnSTYLE_NO;
            
            private global::System.Data.DataColumn columnBYR_ACC_GRP_NAME_EN;
            
            private global::System.Data.DataColumn columnCOLOR_NAME_EN;
            
            private global::System.Data.DataColumn columnCOLOR_CODE;
            
            private global::System.Data.DataColumn columnFAB_TYPE_SNAME;
            
            private global::System.Data.DataColumn columnDYE_MACHINE_NO;
            
            private global::System.Data.DataColumn columnREMARKS;
            
            private global::System.Data.DataColumn columnTTL_RP;
            
            private global::System.Data.DataColumn columnPROD_DT;
            
            private global::System.Data.DataColumn columnLOAD_TIME;
            
            private global::System.Data.DataColumn columnUN_LOAD_TIME;
            
            private global::System.Data.DataColumn columnCHK_ROLL_DT;
            
            private global::System.Data.DataColumn columnCK_ROLL_RCV_DT;
            
            private global::System.Data.DataColumn columnCK_ROLL_FIN_DT;
            
            private global::System.Data.DataColumn columnUN_HOLD_DT;
            
            private global::System.Data.DataColumn columnACT_PROD_DT;
            
            private global::System.Data.DataColumn columnBATCH_QTY;
            
            private global::System.Data.DataColumn columnSL_NO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsDyeingReprocessHistoryDataTable() {
                this.TableName = "dsDyeingReprocessHistory";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsDyeingReprocessHistoryDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dsDyeingReprocessHistoryDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COMP_NAME_ENColumn {
                get {
                    return this.columnCOMP_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COMP_SNAMEColumn {
                get {
                    return this.columnCOMP_SNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn REG_ADD_ENColumn {
                get {
                    return this.columnREG_ADD_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DYE_BATCH_NOColumn {
                get {
                    return this.columnDYE_BATCH_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MC_ORDER_NO_LSTColumn {
                get {
                    return this.columnMC_ORDER_NO_LST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn STYLE_NOColumn {
                get {
                    return this.columnSTYLE_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BYR_ACC_GRP_NAME_ENColumn {
                get {
                    return this.columnBYR_ACC_GRP_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COLOR_NAME_ENColumn {
                get {
                    return this.columnCOLOR_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COLOR_CODEColumn {
                get {
                    return this.columnCOLOR_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FAB_TYPE_SNAMEColumn {
                get {
                    return this.columnFAB_TYPE_SNAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DYE_MACHINE_NOColumn {
                get {
                    return this.columnDYE_MACHINE_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn REMARKSColumn {
                get {
                    return this.columnREMARKS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TTL_RPColumn {
                get {
                    return this.columnTTL_RP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PROD_DTColumn {
                get {
                    return this.columnPROD_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn LOAD_TIMEColumn {
                get {
                    return this.columnLOAD_TIME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn UN_LOAD_TIMEColumn {
                get {
                    return this.columnUN_LOAD_TIME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CHK_ROLL_DTColumn {
                get {
                    return this.columnCHK_ROLL_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CK_ROLL_RCV_DTColumn {
                get {
                    return this.columnCK_ROLL_RCV_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CK_ROLL_FIN_DTColumn {
                get {
                    return this.columnCK_ROLL_FIN_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn UN_HOLD_DTColumn {
                get {
                    return this.columnUN_HOLD_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ACT_PROD_DTColumn {
                get {
                    return this.columnACT_PROD_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BATCH_QTYColumn {
                get {
                    return this.columnBATCH_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SL_NOColumn {
                get {
                    return this.columnSL_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsDyeingReprocessHistoryRow this[int index] {
                get {
                    return ((dsDyeingReprocessHistoryRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsDyeingReprocessHistoryRowChangeEventHandler dsDyeingReprocessHistoryRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsDyeingReprocessHistoryRowChangeEventHandler dsDyeingReprocessHistoryRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsDyeingReprocessHistoryRowChangeEventHandler dsDyeingReprocessHistoryRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsDyeingReprocessHistoryRowChangeEventHandler dsDyeingReprocessHistoryRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AdddsDyeingReprocessHistoryRow(dsDyeingReprocessHistoryRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsDyeingReprocessHistoryRow AdddsDyeingReprocessHistoryRow(
                        string COMP_NAME_EN, 
                        string COMP_SNAME, 
                        string REG_ADD_EN, 
                        string DYE_BATCH_NO, 
                        string MC_ORDER_NO_LST, 
                        string STYLE_NO, 
                        string BYR_ACC_GRP_NAME_EN, 
                        string COLOR_NAME_EN, 
                        string COLOR_CODE, 
                        string FAB_TYPE_SNAME, 
                        string DYE_MACHINE_NO, 
                        string REMARKS, 
                        short TTL_RP, 
                        System.DateTime PROD_DT, 
                        System.DateTime LOAD_TIME, 
                        System.DateTime UN_LOAD_TIME, 
                        System.DateTime CHK_ROLL_DT, 
                        System.DateTime CK_ROLL_RCV_DT, 
                        System.DateTime CK_ROLL_FIN_DT, 
                        System.DateTime UN_HOLD_DT, 
                        System.DateTime ACT_PROD_DT, 
                        decimal BATCH_QTY, 
                        short SL_NO) {
                dsDyeingReprocessHistoryRow rowdsDyeingReprocessHistoryRow = ((dsDyeingReprocessHistoryRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        COMP_NAME_EN,
                        COMP_SNAME,
                        REG_ADD_EN,
                        DYE_BATCH_NO,
                        MC_ORDER_NO_LST,
                        STYLE_NO,
                        BYR_ACC_GRP_NAME_EN,
                        COLOR_NAME_EN,
                        COLOR_CODE,
                        FAB_TYPE_SNAME,
                        DYE_MACHINE_NO,
                        REMARKS,
                        TTL_RP,
                        PROD_DT,
                        LOAD_TIME,
                        UN_LOAD_TIME,
                        CHK_ROLL_DT,
                        CK_ROLL_RCV_DT,
                        CK_ROLL_FIN_DT,
                        UN_HOLD_DT,
                        ACT_PROD_DT,
                        BATCH_QTY,
                        SL_NO};
                rowdsDyeingReprocessHistoryRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdsDyeingReprocessHistoryRow);
                return rowdsDyeingReprocessHistoryRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dsDyeingReprocessHistoryDataTable cln = ((dsDyeingReprocessHistoryDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dsDyeingReprocessHistoryDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnCOMP_NAME_EN = base.Columns["COMP_NAME_EN"];
                this.columnCOMP_SNAME = base.Columns["COMP_SNAME"];
                this.columnREG_ADD_EN = base.Columns["REG_ADD_EN"];
                this.columnDYE_BATCH_NO = base.Columns["DYE_BATCH_NO"];
                this.columnMC_ORDER_NO_LST = base.Columns["MC_ORDER_NO_LST"];
                this.columnSTYLE_NO = base.Columns["STYLE_NO"];
                this.columnBYR_ACC_GRP_NAME_EN = base.Columns["BYR_ACC_GRP_NAME_EN"];
                this.columnCOLOR_NAME_EN = base.Columns["COLOR_NAME_EN"];
                this.columnCOLOR_CODE = base.Columns["COLOR_CODE"];
                this.columnFAB_TYPE_SNAME = base.Columns["FAB_TYPE_SNAME"];
                this.columnDYE_MACHINE_NO = base.Columns["DYE_MACHINE_NO"];
                this.columnREMARKS = base.Columns["REMARKS"];
                this.columnTTL_RP = base.Columns["TTL_RP"];
                this.columnPROD_DT = base.Columns["PROD_DT"];
                this.columnLOAD_TIME = base.Columns["LOAD_TIME"];
                this.columnUN_LOAD_TIME = base.Columns["UN_LOAD_TIME"];
                this.columnCHK_ROLL_DT = base.Columns["CHK_ROLL_DT"];
                this.columnCK_ROLL_RCV_DT = base.Columns["CK_ROLL_RCV_DT"];
                this.columnCK_ROLL_FIN_DT = base.Columns["CK_ROLL_FIN_DT"];
                this.columnUN_HOLD_DT = base.Columns["UN_HOLD_DT"];
                this.columnACT_PROD_DT = base.Columns["ACT_PROD_DT"];
                this.columnBATCH_QTY = base.Columns["BATCH_QTY"];
                this.columnSL_NO = base.Columns["SL_NO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnCOMP_NAME_EN = new global::System.Data.DataColumn("COMP_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOMP_NAME_EN);
                this.columnCOMP_SNAME = new global::System.Data.DataColumn("COMP_SNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOMP_SNAME);
                this.columnREG_ADD_EN = new global::System.Data.DataColumn("REG_ADD_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREG_ADD_EN);
                this.columnDYE_BATCH_NO = new global::System.Data.DataColumn("DYE_BATCH_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDYE_BATCH_NO);
                this.columnMC_ORDER_NO_LST = new global::System.Data.DataColumn("MC_ORDER_NO_LST", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMC_ORDER_NO_LST);
                this.columnSTYLE_NO = new global::System.Data.DataColumn("STYLE_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTYLE_NO);
                this.columnBYR_ACC_GRP_NAME_EN = new global::System.Data.DataColumn("BYR_ACC_GRP_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBYR_ACC_GRP_NAME_EN);
                this.columnCOLOR_NAME_EN = new global::System.Data.DataColumn("COLOR_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOLOR_NAME_EN);
                this.columnCOLOR_CODE = new global::System.Data.DataColumn("COLOR_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOLOR_CODE);
                this.columnFAB_TYPE_SNAME = new global::System.Data.DataColumn("FAB_TYPE_SNAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFAB_TYPE_SNAME);
                this.columnDYE_MACHINE_NO = new global::System.Data.DataColumn("DYE_MACHINE_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDYE_MACHINE_NO);
                this.columnREMARKS = new global::System.Data.DataColumn("REMARKS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREMARKS);
                this.columnTTL_RP = new global::System.Data.DataColumn("TTL_RP", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTTL_RP);
                this.columnPROD_DT = new global::System.Data.DataColumn("PROD_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPROD_DT);
                this.columnLOAD_TIME = new global::System.Data.DataColumn("LOAD_TIME", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLOAD_TIME);
                this.columnUN_LOAD_TIME = new global::System.Data.DataColumn("UN_LOAD_TIME", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUN_LOAD_TIME);
                this.columnCHK_ROLL_DT = new global::System.Data.DataColumn("CHK_ROLL_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCHK_ROLL_DT);
                this.columnCK_ROLL_RCV_DT = new global::System.Data.DataColumn("CK_ROLL_RCV_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCK_ROLL_RCV_DT);
                this.columnCK_ROLL_FIN_DT = new global::System.Data.DataColumn("CK_ROLL_FIN_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCK_ROLL_FIN_DT);
                this.columnUN_HOLD_DT = new global::System.Data.DataColumn("UN_HOLD_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUN_HOLD_DT);
                this.columnACT_PROD_DT = new global::System.Data.DataColumn("ACT_PROD_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnACT_PROD_DT);
                this.columnBATCH_QTY = new global::System.Data.DataColumn("BATCH_QTY", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBATCH_QTY);
                this.columnSL_NO = new global::System.Data.DataColumn("SL_NO", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSL_NO);
                this.ExtendedProperties.Add("Generator_TablePropName", "_dsDyeingReprocessHistory");
                this.ExtendedProperties.Add("Generator_UserTableName", "dsDyeingReprocessHistory");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsDyeingReprocessHistoryRow NewdsDyeingReprocessHistoryRow() {
                return ((dsDyeingReprocessHistoryRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dsDyeingReprocessHistoryRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dsDyeingReprocessHistoryRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dsDyeingReprocessHistoryRowChanged != null)) {
                    this.dsDyeingReprocessHistoryRowChanged(this, new dsDyeingReprocessHistoryRowChangeEvent(((dsDyeingReprocessHistoryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dsDyeingReprocessHistoryRowChanging != null)) {
                    this.dsDyeingReprocessHistoryRowChanging(this, new dsDyeingReprocessHistoryRowChangeEvent(((dsDyeingReprocessHistoryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dsDyeingReprocessHistoryRowDeleted != null)) {
                    this.dsDyeingReprocessHistoryRowDeleted(this, new dsDyeingReprocessHistoryRowChangeEvent(((dsDyeingReprocessHistoryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dsDyeingReprocessHistoryRowDeleting != null)) {
                    this.dsDyeingReprocessHistoryRowDeleting(this, new dsDyeingReprocessHistoryRowChangeEvent(((dsDyeingReprocessHistoryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovedsDyeingReprocessHistoryRow(dsDyeingReprocessHistoryRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsDyeingReprocessHistory ds = new dsDyeingReprocessHistory();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dsDyeingReprocessHistoryDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dsDyeingReprocessHistoryRow : global::System.Data.DataRow {
            
            private dsDyeingReprocessHistoryDataTable tabledsDyeingReprocessHistory;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsDyeingReprocessHistoryRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledsDyeingReprocessHistory = ((dsDyeingReprocessHistoryDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string COMP_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.COMP_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COMP_NAME_EN\' in table \'dsDyeingReprocessHistory\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.COMP_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string COMP_SNAME {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.COMP_SNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COMP_SNAME\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.COMP_SNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string REG_ADD_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.REG_ADD_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REG_ADD_EN\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.REG_ADD_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DYE_BATCH_NO {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.DYE_BATCH_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DYE_BATCH_NO\' in table \'dsDyeingReprocessHistory\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.DYE_BATCH_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string MC_ORDER_NO_LST {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.MC_ORDER_NO_LSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MC_ORDER_NO_LST\' in table \'dsDyeingReprocessHistory\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.MC_ORDER_NO_LSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string STYLE_NO {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.STYLE_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STYLE_NO\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.STYLE_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BYR_ACC_GRP_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.BYR_ACC_GRP_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BYR_ACC_GRP_NAME_EN\' in table \'dsDyeingReprocessHistory\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.BYR_ACC_GRP_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string COLOR_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.COLOR_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COLOR_NAME_EN\' in table \'dsDyeingReprocessHistory\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.COLOR_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string COLOR_CODE {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.COLOR_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COLOR_CODE\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.COLOR_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string FAB_TYPE_SNAME {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.FAB_TYPE_SNAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FAB_TYPE_SNAME\' in table \'dsDyeingReprocessHistory\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.FAB_TYPE_SNAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DYE_MACHINE_NO {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.DYE_MACHINE_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DYE_MACHINE_NO\' in table \'dsDyeingReprocessHistory\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.DYE_MACHINE_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string REMARKS {
                get {
                    try {
                        return ((string)(this[this.tabledsDyeingReprocessHistory.REMARKSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REMARKS\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.REMARKSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short TTL_RP {
                get {
                    try {
                        return ((short)(this[this.tabledsDyeingReprocessHistory.TTL_RPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TTL_RP\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.TTL_RPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime PROD_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsDyeingReprocessHistory.PROD_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PROD_DT\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.PROD_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime LOAD_TIME {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsDyeingReprocessHistory.LOAD_TIMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LOAD_TIME\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.LOAD_TIMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime UN_LOAD_TIME {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsDyeingReprocessHistory.UN_LOAD_TIMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UN_LOAD_TIME\' in table \'dsDyeingReprocessHistory\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.UN_LOAD_TIMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime CHK_ROLL_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsDyeingReprocessHistory.CHK_ROLL_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CHK_ROLL_DT\' in table \'dsDyeingReprocessHistory\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.CHK_ROLL_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime CK_ROLL_RCV_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsDyeingReprocessHistory.CK_ROLL_RCV_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CK_ROLL_RCV_DT\' in table \'dsDyeingReprocessHistory\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.CK_ROLL_RCV_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime CK_ROLL_FIN_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsDyeingReprocessHistory.CK_ROLL_FIN_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CK_ROLL_FIN_DT\' in table \'dsDyeingReprocessHistory\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.CK_ROLL_FIN_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime UN_HOLD_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsDyeingReprocessHistory.UN_HOLD_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UN_HOLD_DT\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.UN_HOLD_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime ACT_PROD_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsDyeingReprocessHistory.ACT_PROD_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ACT_PROD_DT\' in table \'dsDyeingReprocessHistory\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.ACT_PROD_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal BATCH_QTY {
                get {
                    try {
                        return ((decimal)(this[this.tabledsDyeingReprocessHistory.BATCH_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BATCH_QTY\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.BATCH_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public short SL_NO {
                get {
                    try {
                        return ((short)(this[this.tabledsDyeingReprocessHistory.SL_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SL_NO\' in table \'dsDyeingReprocessHistory\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsDyeingReprocessHistory.SL_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOMP_NAME_ENNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.COMP_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOMP_NAME_ENNull() {
                this[this.tabledsDyeingReprocessHistory.COMP_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOMP_SNAMENull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.COMP_SNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOMP_SNAMENull() {
                this[this.tabledsDyeingReprocessHistory.COMP_SNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsREG_ADD_ENNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.REG_ADD_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetREG_ADD_ENNull() {
                this[this.tabledsDyeingReprocessHistory.REG_ADD_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDYE_BATCH_NONull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.DYE_BATCH_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDYE_BATCH_NONull() {
                this[this.tabledsDyeingReprocessHistory.DYE_BATCH_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMC_ORDER_NO_LSTNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.MC_ORDER_NO_LSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMC_ORDER_NO_LSTNull() {
                this[this.tabledsDyeingReprocessHistory.MC_ORDER_NO_LSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSTYLE_NONull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.STYLE_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSTYLE_NONull() {
                this[this.tabledsDyeingReprocessHistory.STYLE_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBYR_ACC_GRP_NAME_ENNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.BYR_ACC_GRP_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBYR_ACC_GRP_NAME_ENNull() {
                this[this.tabledsDyeingReprocessHistory.BYR_ACC_GRP_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOLOR_NAME_ENNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.COLOR_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOLOR_NAME_ENNull() {
                this[this.tabledsDyeingReprocessHistory.COLOR_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOLOR_CODENull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.COLOR_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOLOR_CODENull() {
                this[this.tabledsDyeingReprocessHistory.COLOR_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFAB_TYPE_SNAMENull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.FAB_TYPE_SNAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFAB_TYPE_SNAMENull() {
                this[this.tabledsDyeingReprocessHistory.FAB_TYPE_SNAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDYE_MACHINE_NONull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.DYE_MACHINE_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDYE_MACHINE_NONull() {
                this[this.tabledsDyeingReprocessHistory.DYE_MACHINE_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsREMARKSNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.REMARKSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetREMARKSNull() {
                this[this.tabledsDyeingReprocessHistory.REMARKSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTTL_RPNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.TTL_RPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTTL_RPNull() {
                this[this.tabledsDyeingReprocessHistory.TTL_RPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPROD_DTNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.PROD_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPROD_DTNull() {
                this[this.tabledsDyeingReprocessHistory.PROD_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsLOAD_TIMENull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.LOAD_TIMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetLOAD_TIMENull() {
                this[this.tabledsDyeingReprocessHistory.LOAD_TIMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsUN_LOAD_TIMENull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.UN_LOAD_TIMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetUN_LOAD_TIMENull() {
                this[this.tabledsDyeingReprocessHistory.UN_LOAD_TIMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCHK_ROLL_DTNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.CHK_ROLL_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCHK_ROLL_DTNull() {
                this[this.tabledsDyeingReprocessHistory.CHK_ROLL_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCK_ROLL_RCV_DTNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.CK_ROLL_RCV_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCK_ROLL_RCV_DTNull() {
                this[this.tabledsDyeingReprocessHistory.CK_ROLL_RCV_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCK_ROLL_FIN_DTNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.CK_ROLL_FIN_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCK_ROLL_FIN_DTNull() {
                this[this.tabledsDyeingReprocessHistory.CK_ROLL_FIN_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsUN_HOLD_DTNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.UN_HOLD_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetUN_HOLD_DTNull() {
                this[this.tabledsDyeingReprocessHistory.UN_HOLD_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsACT_PROD_DTNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.ACT_PROD_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetACT_PROD_DTNull() {
                this[this.tabledsDyeingReprocessHistory.ACT_PROD_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBATCH_QTYNull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.BATCH_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBATCH_QTYNull() {
                this[this.tabledsDyeingReprocessHistory.BATCH_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSL_NONull() {
                return this.IsNull(this.tabledsDyeingReprocessHistory.SL_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSL_NONull() {
                this[this.tabledsDyeingReprocessHistory.SL_NOColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dsDyeingReprocessHistoryRowChangeEvent : global::System.EventArgs {
            
            private dsDyeingReprocessHistoryRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsDyeingReprocessHistoryRowChangeEvent(dsDyeingReprocessHistoryRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsDyeingReprocessHistoryRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591