//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ERPSolution.Areas.Knitting.Reports.DS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsKntYrnIssStatement")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsKntYrnIssStatement : global::System.Data.DataSet {
        
        private dsKntYrnIssStatementDataTable tabledsKntYrnIssStatement;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dsKntYrnIssStatement() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dsKntYrnIssStatement(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dsKntYrnIssStatement"] != null)) {
                    base.Tables.Add(new dsKntYrnIssStatementDataTable(ds.Tables["dsKntYrnIssStatement"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dsKntYrnIssStatementDataTable _dsKntYrnIssStatement {
            get {
                return this.tabledsKntYrnIssStatement;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsKntYrnIssStatement cln = ((dsKntYrnIssStatement)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dsKntYrnIssStatement"] != null)) {
                    base.Tables.Add(new dsKntYrnIssStatementDataTable(ds.Tables["dsKntYrnIssStatement"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledsKntYrnIssStatement = ((dsKntYrnIssStatementDataTable)(base.Tables["dsKntYrnIssStatement"]));
            if ((initTable == true)) {
                if ((this.tabledsKntYrnIssStatement != null)) {
                    this.tabledsKntYrnIssStatement.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsKntYrnIssStatement";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsKntYrnIssStatement.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledsKntYrnIssStatement = new dsKntYrnIssStatementDataTable();
            base.Tables.Add(this.tabledsKntYrnIssStatement);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerialize_dsKntYrnIssStatement() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsKntYrnIssStatement ds = new dsKntYrnIssStatement();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dsKntYrnIssStatementRowChangeEventHandler(object sender, dsKntYrnIssStatementRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dsKntYrnIssStatementDataTable : global::System.Data.TypedTableBase<dsKntYrnIssStatementRow> {
            
            private global::System.Data.DataColumn columnBUYER_NAME_EN;
            
            private global::System.Data.DataColumn columnORDER_NO;
            
            private global::System.Data.DataColumn columnREQ_TYPE_NAME;
            
            private global::System.Data.DataColumn columnEMPLOYEE_CODE;
            
            private global::System.Data.DataColumn columnEMP_FULL_NAME_EN;
            
            private global::System.Data.DataColumn columnISS_CHALAN_DT;
            
            private global::System.Data.DataColumn columnSTORE_NAME_EN;
            
            private global::System.Data.DataColumn columnREMARKS;
            
            private global::System.Data.DataColumn columnITEM_NAME_EN;
            
            private global::System.Data.DataColumn columnBRAND_NAME_EN;
            
            private global::System.Data.DataColumn columnYRN_LOT_NO;
            
            private global::System.Data.DataColumn columnPACK_ISS_QTY;
            
            private global::System.Data.DataColumn columnPACK_MOU_CODE;
            
            private global::System.Data.DataColumn columnQTY_PER_PACK;
            
            private global::System.Data.DataColumn columnQTY_MOU_CODE;
            
            private global::System.Data.DataColumn columnLOOSE_QTY;
            
            private global::System.Data.DataColumn columnISSUE_QTY;
            
            private global::System.Data.DataColumn columnRQD_CONE_QTY;
            
            private global::System.Data.DataColumn columnRQD_YRN_QTY;
            
            private global::System.Data.DataColumn columnSUP_TRD_NAME_EN;
            
            private global::System.Data.DataColumn columnISS_CHALAN_NO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsKntYrnIssStatementDataTable() {
                this.TableName = "dsKntYrnIssStatement";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsKntYrnIssStatementDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dsKntYrnIssStatementDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BUYER_NAME_ENColumn {
                get {
                    return this.columnBUYER_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ORDER_NOColumn {
                get {
                    return this.columnORDER_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn REQ_TYPE_NAMEColumn {
                get {
                    return this.columnREQ_TYPE_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn EMPLOYEE_CODEColumn {
                get {
                    return this.columnEMPLOYEE_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn EMP_FULL_NAME_ENColumn {
                get {
                    return this.columnEMP_FULL_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ISS_CHALAN_DTColumn {
                get {
                    return this.columnISS_CHALAN_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn STORE_NAME_ENColumn {
                get {
                    return this.columnSTORE_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn REMARKSColumn {
                get {
                    return this.columnREMARKS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ITEM_NAME_ENColumn {
                get {
                    return this.columnITEM_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BRAND_NAME_ENColumn {
                get {
                    return this.columnBRAND_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn YRN_LOT_NOColumn {
                get {
                    return this.columnYRN_LOT_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PACK_ISS_QTYColumn {
                get {
                    return this.columnPACK_ISS_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PACK_MOU_CODEColumn {
                get {
                    return this.columnPACK_MOU_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QTY_PER_PACKColumn {
                get {
                    return this.columnQTY_PER_PACK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QTY_MOU_CODEColumn {
                get {
                    return this.columnQTY_MOU_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn LOOSE_QTYColumn {
                get {
                    return this.columnLOOSE_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ISSUE_QTYColumn {
                get {
                    return this.columnISSUE_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RQD_CONE_QTYColumn {
                get {
                    return this.columnRQD_CONE_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RQD_YRN_QTYColumn {
                get {
                    return this.columnRQD_YRN_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SUP_TRD_NAME_ENColumn {
                get {
                    return this.columnSUP_TRD_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ISS_CHALAN_NOColumn {
                get {
                    return this.columnISS_CHALAN_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsKntYrnIssStatementRow this[int index] {
                get {
                    return ((dsKntYrnIssStatementRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsKntYrnIssStatementRowChangeEventHandler dsKntYrnIssStatementRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsKntYrnIssStatementRowChangeEventHandler dsKntYrnIssStatementRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsKntYrnIssStatementRowChangeEventHandler dsKntYrnIssStatementRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsKntYrnIssStatementRowChangeEventHandler dsKntYrnIssStatementRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AdddsKntYrnIssStatementRow(dsKntYrnIssStatementRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsKntYrnIssStatementRow AdddsKntYrnIssStatementRow(
                        string BUYER_NAME_EN, 
                        string ORDER_NO, 
                        string REQ_TYPE_NAME, 
                        string EMPLOYEE_CODE, 
                        string EMP_FULL_NAME_EN, 
                        System.DateTime ISS_CHALAN_DT, 
                        string STORE_NAME_EN, 
                        string REMARKS, 
                        string ITEM_NAME_EN, 
                        string BRAND_NAME_EN, 
                        string YRN_LOT_NO, 
                        decimal PACK_ISS_QTY, 
                        string PACK_MOU_CODE, 
                        decimal QTY_PER_PACK, 
                        string QTY_MOU_CODE, 
                        decimal LOOSE_QTY, 
                        decimal ISSUE_QTY, 
                        int RQD_CONE_QTY, 
                        decimal RQD_YRN_QTY, 
                        string SUP_TRD_NAME_EN, 
                        string ISS_CHALAN_NO) {
                dsKntYrnIssStatementRow rowdsKntYrnIssStatementRow = ((dsKntYrnIssStatementRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        BUYER_NAME_EN,
                        ORDER_NO,
                        REQ_TYPE_NAME,
                        EMPLOYEE_CODE,
                        EMP_FULL_NAME_EN,
                        ISS_CHALAN_DT,
                        STORE_NAME_EN,
                        REMARKS,
                        ITEM_NAME_EN,
                        BRAND_NAME_EN,
                        YRN_LOT_NO,
                        PACK_ISS_QTY,
                        PACK_MOU_CODE,
                        QTY_PER_PACK,
                        QTY_MOU_CODE,
                        LOOSE_QTY,
                        ISSUE_QTY,
                        RQD_CONE_QTY,
                        RQD_YRN_QTY,
                        SUP_TRD_NAME_EN,
                        ISS_CHALAN_NO};
                rowdsKntYrnIssStatementRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdsKntYrnIssStatementRow);
                return rowdsKntYrnIssStatementRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dsKntYrnIssStatementDataTable cln = ((dsKntYrnIssStatementDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dsKntYrnIssStatementDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnBUYER_NAME_EN = base.Columns["BUYER_NAME_EN"];
                this.columnORDER_NO = base.Columns["ORDER_NO"];
                this.columnREQ_TYPE_NAME = base.Columns["REQ_TYPE_NAME"];
                this.columnEMPLOYEE_CODE = base.Columns["EMPLOYEE_CODE"];
                this.columnEMP_FULL_NAME_EN = base.Columns["EMP_FULL_NAME_EN"];
                this.columnISS_CHALAN_DT = base.Columns["ISS_CHALAN_DT"];
                this.columnSTORE_NAME_EN = base.Columns["STORE_NAME_EN"];
                this.columnREMARKS = base.Columns["REMARKS"];
                this.columnITEM_NAME_EN = base.Columns["ITEM_NAME_EN"];
                this.columnBRAND_NAME_EN = base.Columns["BRAND_NAME_EN"];
                this.columnYRN_LOT_NO = base.Columns["YRN_LOT_NO"];
                this.columnPACK_ISS_QTY = base.Columns["PACK_ISS_QTY"];
                this.columnPACK_MOU_CODE = base.Columns["PACK_MOU_CODE"];
                this.columnQTY_PER_PACK = base.Columns["QTY_PER_PACK"];
                this.columnQTY_MOU_CODE = base.Columns["QTY_MOU_CODE"];
                this.columnLOOSE_QTY = base.Columns["LOOSE_QTY"];
                this.columnISSUE_QTY = base.Columns["ISSUE_QTY"];
                this.columnRQD_CONE_QTY = base.Columns["RQD_CONE_QTY"];
                this.columnRQD_YRN_QTY = base.Columns["RQD_YRN_QTY"];
                this.columnSUP_TRD_NAME_EN = base.Columns["SUP_TRD_NAME_EN"];
                this.columnISS_CHALAN_NO = base.Columns["ISS_CHALAN_NO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnBUYER_NAME_EN = new global::System.Data.DataColumn("BUYER_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBUYER_NAME_EN);
                this.columnORDER_NO = new global::System.Data.DataColumn("ORDER_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnORDER_NO);
                this.columnREQ_TYPE_NAME = new global::System.Data.DataColumn("REQ_TYPE_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREQ_TYPE_NAME);
                this.columnEMPLOYEE_CODE = new global::System.Data.DataColumn("EMPLOYEE_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEMPLOYEE_CODE);
                this.columnEMP_FULL_NAME_EN = new global::System.Data.DataColumn("EMP_FULL_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEMP_FULL_NAME_EN);
                this.columnISS_CHALAN_DT = new global::System.Data.DataColumn("ISS_CHALAN_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnISS_CHALAN_DT);
                this.columnSTORE_NAME_EN = new global::System.Data.DataColumn("STORE_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTORE_NAME_EN);
                this.columnREMARKS = new global::System.Data.DataColumn("REMARKS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREMARKS);
                this.columnITEM_NAME_EN = new global::System.Data.DataColumn("ITEM_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnITEM_NAME_EN);
                this.columnBRAND_NAME_EN = new global::System.Data.DataColumn("BRAND_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBRAND_NAME_EN);
                this.columnYRN_LOT_NO = new global::System.Data.DataColumn("YRN_LOT_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYRN_LOT_NO);
                this.columnPACK_ISS_QTY = new global::System.Data.DataColumn("PACK_ISS_QTY", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPACK_ISS_QTY);
                this.columnPACK_MOU_CODE = new global::System.Data.DataColumn("PACK_MOU_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPACK_MOU_CODE);
                this.columnQTY_PER_PACK = new global::System.Data.DataColumn("QTY_PER_PACK", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQTY_PER_PACK);
                this.columnQTY_MOU_CODE = new global::System.Data.DataColumn("QTY_MOU_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQTY_MOU_CODE);
                this.columnLOOSE_QTY = new global::System.Data.DataColumn("LOOSE_QTY", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLOOSE_QTY);
                this.columnISSUE_QTY = new global::System.Data.DataColumn("ISSUE_QTY", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnISSUE_QTY);
                this.columnRQD_CONE_QTY = new global::System.Data.DataColumn("RQD_CONE_QTY", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRQD_CONE_QTY);
                this.columnRQD_YRN_QTY = new global::System.Data.DataColumn("RQD_YRN_QTY", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRQD_YRN_QTY);
                this.columnSUP_TRD_NAME_EN = new global::System.Data.DataColumn("SUP_TRD_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSUP_TRD_NAME_EN);
                this.columnISS_CHALAN_NO = new global::System.Data.DataColumn("ISS_CHALAN_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnISS_CHALAN_NO);
                this.ExtendedProperties.Add("Generator_TablePropName", "_dsKntYrnIssStatement");
                this.ExtendedProperties.Add("Generator_UserTableName", "dsKntYrnIssStatement");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsKntYrnIssStatementRow NewdsKntYrnIssStatementRow() {
                return ((dsKntYrnIssStatementRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dsKntYrnIssStatementRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dsKntYrnIssStatementRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dsKntYrnIssStatementRowChanged != null)) {
                    this.dsKntYrnIssStatementRowChanged(this, new dsKntYrnIssStatementRowChangeEvent(((dsKntYrnIssStatementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dsKntYrnIssStatementRowChanging != null)) {
                    this.dsKntYrnIssStatementRowChanging(this, new dsKntYrnIssStatementRowChangeEvent(((dsKntYrnIssStatementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dsKntYrnIssStatementRowDeleted != null)) {
                    this.dsKntYrnIssStatementRowDeleted(this, new dsKntYrnIssStatementRowChangeEvent(((dsKntYrnIssStatementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dsKntYrnIssStatementRowDeleting != null)) {
                    this.dsKntYrnIssStatementRowDeleting(this, new dsKntYrnIssStatementRowChangeEvent(((dsKntYrnIssStatementRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovedsKntYrnIssStatementRow(dsKntYrnIssStatementRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsKntYrnIssStatement ds = new dsKntYrnIssStatement();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dsKntYrnIssStatementDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dsKntYrnIssStatementRow : global::System.Data.DataRow {
            
            private dsKntYrnIssStatementDataTable tabledsKntYrnIssStatement;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsKntYrnIssStatementRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledsKntYrnIssStatement = ((dsKntYrnIssStatementDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BUYER_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.BUYER_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BUYER_NAME_EN\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.BUYER_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ORDER_NO {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.ORDER_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ORDER_NO\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.ORDER_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string REQ_TYPE_NAME {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.REQ_TYPE_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REQ_TYPE_NAME\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.REQ_TYPE_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string EMPLOYEE_CODE {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.EMPLOYEE_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EMPLOYEE_CODE\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.EMPLOYEE_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string EMP_FULL_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.EMP_FULL_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EMP_FULL_NAME_EN\' in table \'dsKntYrnIssStatement\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.EMP_FULL_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime ISS_CHALAN_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsKntYrnIssStatement.ISS_CHALAN_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ISS_CHALAN_DT\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.ISS_CHALAN_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string STORE_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.STORE_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STORE_NAME_EN\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.STORE_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string REMARKS {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.REMARKSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REMARKS\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.REMARKSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ITEM_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.ITEM_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ITEM_NAME_EN\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.ITEM_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BRAND_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.BRAND_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BRAND_NAME_EN\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.BRAND_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string YRN_LOT_NO {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.YRN_LOT_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'YRN_LOT_NO\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.YRN_LOT_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal PACK_ISS_QTY {
                get {
                    try {
                        return ((decimal)(this[this.tabledsKntYrnIssStatement.PACK_ISS_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PACK_ISS_QTY\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.PACK_ISS_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PACK_MOU_CODE {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.PACK_MOU_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PACK_MOU_CODE\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.PACK_MOU_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal QTY_PER_PACK {
                get {
                    try {
                        return ((decimal)(this[this.tabledsKntYrnIssStatement.QTY_PER_PACKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QTY_PER_PACK\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.QTY_PER_PACKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string QTY_MOU_CODE {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.QTY_MOU_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QTY_MOU_CODE\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.QTY_MOU_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal LOOSE_QTY {
                get {
                    try {
                        return ((decimal)(this[this.tabledsKntYrnIssStatement.LOOSE_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LOOSE_QTY\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.LOOSE_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ISSUE_QTY {
                get {
                    try {
                        return ((decimal)(this[this.tabledsKntYrnIssStatement.ISSUE_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ISSUE_QTY\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.ISSUE_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int RQD_CONE_QTY {
                get {
                    try {
                        return ((int)(this[this.tabledsKntYrnIssStatement.RQD_CONE_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RQD_CONE_QTY\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.RQD_CONE_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal RQD_YRN_QTY {
                get {
                    try {
                        return ((decimal)(this[this.tabledsKntYrnIssStatement.RQD_YRN_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RQD_YRN_QTY\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.RQD_YRN_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SUP_TRD_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.SUP_TRD_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SUP_TRD_NAME_EN\' in table \'dsKntYrnIssStatement\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.SUP_TRD_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ISS_CHALAN_NO {
                get {
                    try {
                        return ((string)(this[this.tabledsKntYrnIssStatement.ISS_CHALAN_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ISS_CHALAN_NO\' in table \'dsKntYrnIssStatement\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsKntYrnIssStatement.ISS_CHALAN_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBUYER_NAME_ENNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.BUYER_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBUYER_NAME_ENNull() {
                this[this.tabledsKntYrnIssStatement.BUYER_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsORDER_NONull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.ORDER_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetORDER_NONull() {
                this[this.tabledsKntYrnIssStatement.ORDER_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsREQ_TYPE_NAMENull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.REQ_TYPE_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetREQ_TYPE_NAMENull() {
                this[this.tabledsKntYrnIssStatement.REQ_TYPE_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsEMPLOYEE_CODENull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.EMPLOYEE_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetEMPLOYEE_CODENull() {
                this[this.tabledsKntYrnIssStatement.EMPLOYEE_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsEMP_FULL_NAME_ENNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.EMP_FULL_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetEMP_FULL_NAME_ENNull() {
                this[this.tabledsKntYrnIssStatement.EMP_FULL_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsISS_CHALAN_DTNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.ISS_CHALAN_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetISS_CHALAN_DTNull() {
                this[this.tabledsKntYrnIssStatement.ISS_CHALAN_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSTORE_NAME_ENNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.STORE_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSTORE_NAME_ENNull() {
                this[this.tabledsKntYrnIssStatement.STORE_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsREMARKSNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.REMARKSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetREMARKSNull() {
                this[this.tabledsKntYrnIssStatement.REMARKSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsITEM_NAME_ENNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.ITEM_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetITEM_NAME_ENNull() {
                this[this.tabledsKntYrnIssStatement.ITEM_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBRAND_NAME_ENNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.BRAND_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBRAND_NAME_ENNull() {
                this[this.tabledsKntYrnIssStatement.BRAND_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsYRN_LOT_NONull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.YRN_LOT_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetYRN_LOT_NONull() {
                this[this.tabledsKntYrnIssStatement.YRN_LOT_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPACK_ISS_QTYNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.PACK_ISS_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPACK_ISS_QTYNull() {
                this[this.tabledsKntYrnIssStatement.PACK_ISS_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPACK_MOU_CODENull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.PACK_MOU_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPACK_MOU_CODENull() {
                this[this.tabledsKntYrnIssStatement.PACK_MOU_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQTY_PER_PACKNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.QTY_PER_PACKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQTY_PER_PACKNull() {
                this[this.tabledsKntYrnIssStatement.QTY_PER_PACKColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQTY_MOU_CODENull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.QTY_MOU_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQTY_MOU_CODENull() {
                this[this.tabledsKntYrnIssStatement.QTY_MOU_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsLOOSE_QTYNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.LOOSE_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetLOOSE_QTYNull() {
                this[this.tabledsKntYrnIssStatement.LOOSE_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsISSUE_QTYNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.ISSUE_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetISSUE_QTYNull() {
                this[this.tabledsKntYrnIssStatement.ISSUE_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRQD_CONE_QTYNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.RQD_CONE_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRQD_CONE_QTYNull() {
                this[this.tabledsKntYrnIssStatement.RQD_CONE_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRQD_YRN_QTYNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.RQD_YRN_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRQD_YRN_QTYNull() {
                this[this.tabledsKntYrnIssStatement.RQD_YRN_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSUP_TRD_NAME_ENNull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.SUP_TRD_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSUP_TRD_NAME_ENNull() {
                this[this.tabledsKntYrnIssStatement.SUP_TRD_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsISS_CHALAN_NONull() {
                return this.IsNull(this.tabledsKntYrnIssStatement.ISS_CHALAN_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetISS_CHALAN_NONull() {
                this[this.tabledsKntYrnIssStatement.ISS_CHALAN_NOColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dsKntYrnIssStatementRowChangeEvent : global::System.EventArgs {
            
            private dsKntYrnIssStatementRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsKntYrnIssStatementRowChangeEvent(dsKntYrnIssStatementRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsKntYrnIssStatementRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591