//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ERPSolution.Areas.Merchandising.Reports.DS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsAccPurchaseRequisition")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsAccPurchaseRequisition : global::System.Data.DataSet {
        
        private dsAccPurchaseRequisitionDataTable tabledsAccPurchaseRequisition;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public dsAccPurchaseRequisition() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected dsAccPurchaseRequisition(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["dsAccPurchaseRequisition"] != null)) {
                    base.Tables.Add(new dsAccPurchaseRequisitionDataTable(ds.Tables["dsAccPurchaseRequisition"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public dsAccPurchaseRequisitionDataTable _dsAccPurchaseRequisition {
            get {
                return this.tabledsAccPurchaseRequisition;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsAccPurchaseRequisition cln = ((dsAccPurchaseRequisition)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["dsAccPurchaseRequisition"] != null)) {
                    base.Tables.Add(new dsAccPurchaseRequisitionDataTable(ds.Tables["dsAccPurchaseRequisition"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabledsAccPurchaseRequisition = ((dsAccPurchaseRequisitionDataTable)(base.Tables["dsAccPurchaseRequisition"]));
            if ((initTable == true)) {
                if ((this.tabledsAccPurchaseRequisition != null)) {
                    this.tabledsAccPurchaseRequisition.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsAccPurchaseRequisition";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsAccPurchaseRequisition.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabledsAccPurchaseRequisition = new dsAccPurchaseRequisitionDataTable();
            base.Tables.Add(this.tabledsAccPurchaseRequisition);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerialize_dsAccPurchaseRequisition() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsAccPurchaseRequisition ds = new dsAccPurchaseRequisition();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void dsAccPurchaseRequisitionRowChangeEventHandler(object sender, dsAccPurchaseRequisitionRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class dsAccPurchaseRequisitionDataTable : global::System.Data.TypedTableBase<dsAccPurchaseRequisitionRow> {
            
            private global::System.Data.DataColumn columnBYR_ACC_GRP_NAME_EN;
            
            private global::System.Data.DataColumn columnBYR_ACC_NAME_EN;
            
            private global::System.Data.DataColumn columnSTYLE_NO;
            
            private global::System.Data.DataColumn columnMC_ORDER_NO_LST;
            
            private global::System.Data.DataColumn columnPURC_REQ_NO;
            
            private global::System.Data.DataColumn columnPURC_REQ_DT;
            
            private global::System.Data.DataColumn columnITEM_NAME_EN;
            
            private global::System.Data.DataColumn columnCOLOR_NAME_EN;
            
            private global::System.Data.DataColumn columnSIZE_CODE;
            
            private global::System.Data.DataColumn columnPROD_COLOR_NAME_EN;
            
            private global::System.Data.DataColumn columnPROD_SIZE_CODE;
            
            private global::System.Data.DataColumn columnITEM_SPEC_AUTO;
            
            private global::System.Data.DataColumn columnITEM_CODE;
            
            private global::System.Data.DataColumn columnPARTICULARS;
            
            private global::System.Data.DataColumn columnRQD_QTY;
            
            private global::System.Data.DataColumn columnORDER_QTY;
            
            private global::System.Data.DataColumn columnMOU_CODE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAccPurchaseRequisitionDataTable() {
                this.TableName = "dsAccPurchaseRequisition";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsAccPurchaseRequisitionDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected dsAccPurchaseRequisitionDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BYR_ACC_GRP_NAME_ENColumn {
                get {
                    return this.columnBYR_ACC_GRP_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BYR_ACC_NAME_ENColumn {
                get {
                    return this.columnBYR_ACC_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn STYLE_NOColumn {
                get {
                    return this.columnSTYLE_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MC_ORDER_NO_LSTColumn {
                get {
                    return this.columnMC_ORDER_NO_LST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PURC_REQ_NOColumn {
                get {
                    return this.columnPURC_REQ_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PURC_REQ_DTColumn {
                get {
                    return this.columnPURC_REQ_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ITEM_NAME_ENColumn {
                get {
                    return this.columnITEM_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn COLOR_NAME_ENColumn {
                get {
                    return this.columnCOLOR_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn SIZE_CODEColumn {
                get {
                    return this.columnSIZE_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PROD_COLOR_NAME_ENColumn {
                get {
                    return this.columnPROD_COLOR_NAME_EN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PROD_SIZE_CODEColumn {
                get {
                    return this.columnPROD_SIZE_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ITEM_SPEC_AUTOColumn {
                get {
                    return this.columnITEM_SPEC_AUTO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ITEM_CODEColumn {
                get {
                    return this.columnITEM_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PARTICULARSColumn {
                get {
                    return this.columnPARTICULARS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn RQD_QTYColumn {
                get {
                    return this.columnRQD_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ORDER_QTYColumn {
                get {
                    return this.columnORDER_QTY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MOU_CODEColumn {
                get {
                    return this.columnMOU_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAccPurchaseRequisitionRow this[int index] {
                get {
                    return ((dsAccPurchaseRequisitionRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsAccPurchaseRequisitionRowChangeEventHandler dsAccPurchaseRequisitionRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsAccPurchaseRequisitionRowChangeEventHandler dsAccPurchaseRequisitionRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsAccPurchaseRequisitionRowChangeEventHandler dsAccPurchaseRequisitionRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event dsAccPurchaseRequisitionRowChangeEventHandler dsAccPurchaseRequisitionRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AdddsAccPurchaseRequisitionRow(dsAccPurchaseRequisitionRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAccPurchaseRequisitionRow AdddsAccPurchaseRequisitionRow(
                        string BYR_ACC_GRP_NAME_EN, 
                        string BYR_ACC_NAME_EN, 
                        string STYLE_NO, 
                        string MC_ORDER_NO_LST, 
                        string PURC_REQ_NO, 
                        System.DateTime PURC_REQ_DT, 
                        string ITEM_NAME_EN, 
                        string COLOR_NAME_EN, 
                        string SIZE_CODE, 
                        string PROD_COLOR_NAME_EN, 
                        string PROD_SIZE_CODE, 
                        string ITEM_SPEC_AUTO, 
                        string ITEM_CODE, 
                        string PARTICULARS, 
                        decimal RQD_QTY, 
                        decimal ORDER_QTY, 
                        string MOU_CODE) {
                dsAccPurchaseRequisitionRow rowdsAccPurchaseRequisitionRow = ((dsAccPurchaseRequisitionRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        BYR_ACC_GRP_NAME_EN,
                        BYR_ACC_NAME_EN,
                        STYLE_NO,
                        MC_ORDER_NO_LST,
                        PURC_REQ_NO,
                        PURC_REQ_DT,
                        ITEM_NAME_EN,
                        COLOR_NAME_EN,
                        SIZE_CODE,
                        PROD_COLOR_NAME_EN,
                        PROD_SIZE_CODE,
                        ITEM_SPEC_AUTO,
                        ITEM_CODE,
                        PARTICULARS,
                        RQD_QTY,
                        ORDER_QTY,
                        MOU_CODE};
                rowdsAccPurchaseRequisitionRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowdsAccPurchaseRequisitionRow);
                return rowdsAccPurchaseRequisitionRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                dsAccPurchaseRequisitionDataTable cln = ((dsAccPurchaseRequisitionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new dsAccPurchaseRequisitionDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnBYR_ACC_GRP_NAME_EN = base.Columns["BYR_ACC_GRP_NAME_EN"];
                this.columnBYR_ACC_NAME_EN = base.Columns["BYR_ACC_NAME_EN"];
                this.columnSTYLE_NO = base.Columns["STYLE_NO"];
                this.columnMC_ORDER_NO_LST = base.Columns["MC_ORDER_NO_LST"];
                this.columnPURC_REQ_NO = base.Columns["PURC_REQ_NO"];
                this.columnPURC_REQ_DT = base.Columns["PURC_REQ_DT"];
                this.columnITEM_NAME_EN = base.Columns["ITEM_NAME_EN"];
                this.columnCOLOR_NAME_EN = base.Columns["COLOR_NAME_EN"];
                this.columnSIZE_CODE = base.Columns["SIZE_CODE"];
                this.columnPROD_COLOR_NAME_EN = base.Columns["PROD_COLOR_NAME_EN"];
                this.columnPROD_SIZE_CODE = base.Columns["PROD_SIZE_CODE"];
                this.columnITEM_SPEC_AUTO = base.Columns["ITEM_SPEC_AUTO"];
                this.columnITEM_CODE = base.Columns["ITEM_CODE"];
                this.columnPARTICULARS = base.Columns["PARTICULARS"];
                this.columnRQD_QTY = base.Columns["RQD_QTY"];
                this.columnORDER_QTY = base.Columns["ORDER_QTY"];
                this.columnMOU_CODE = base.Columns["MOU_CODE"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnBYR_ACC_GRP_NAME_EN = new global::System.Data.DataColumn("BYR_ACC_GRP_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBYR_ACC_GRP_NAME_EN);
                this.columnBYR_ACC_NAME_EN = new global::System.Data.DataColumn("BYR_ACC_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBYR_ACC_NAME_EN);
                this.columnSTYLE_NO = new global::System.Data.DataColumn("STYLE_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTYLE_NO);
                this.columnMC_ORDER_NO_LST = new global::System.Data.DataColumn("MC_ORDER_NO_LST", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMC_ORDER_NO_LST);
                this.columnPURC_REQ_NO = new global::System.Data.DataColumn("PURC_REQ_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPURC_REQ_NO);
                this.columnPURC_REQ_DT = new global::System.Data.DataColumn("PURC_REQ_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPURC_REQ_DT);
                this.columnITEM_NAME_EN = new global::System.Data.DataColumn("ITEM_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnITEM_NAME_EN);
                this.columnCOLOR_NAME_EN = new global::System.Data.DataColumn("COLOR_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOLOR_NAME_EN);
                this.columnSIZE_CODE = new global::System.Data.DataColumn("SIZE_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSIZE_CODE);
                this.columnPROD_COLOR_NAME_EN = new global::System.Data.DataColumn("PROD_COLOR_NAME_EN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPROD_COLOR_NAME_EN);
                this.columnPROD_SIZE_CODE = new global::System.Data.DataColumn("PROD_SIZE_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPROD_SIZE_CODE);
                this.columnITEM_SPEC_AUTO = new global::System.Data.DataColumn("ITEM_SPEC_AUTO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnITEM_SPEC_AUTO);
                this.columnITEM_CODE = new global::System.Data.DataColumn("ITEM_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnITEM_CODE);
                this.columnPARTICULARS = new global::System.Data.DataColumn("PARTICULARS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPARTICULARS);
                this.columnRQD_QTY = new global::System.Data.DataColumn("RQD_QTY", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRQD_QTY);
                this.columnORDER_QTY = new global::System.Data.DataColumn("ORDER_QTY", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnORDER_QTY);
                this.columnMOU_CODE = new global::System.Data.DataColumn("MOU_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMOU_CODE);
                this.ExtendedProperties.Add("Generator_TablePropName", "_dsAccPurchaseRequisition");
                this.ExtendedProperties.Add("Generator_UserTableName", "dsAccPurchaseRequisition");
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAccPurchaseRequisitionRow NewdsAccPurchaseRequisitionRow() {
                return ((dsAccPurchaseRequisitionRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new dsAccPurchaseRequisitionRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(dsAccPurchaseRequisitionRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.dsAccPurchaseRequisitionRowChanged != null)) {
                    this.dsAccPurchaseRequisitionRowChanged(this, new dsAccPurchaseRequisitionRowChangeEvent(((dsAccPurchaseRequisitionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.dsAccPurchaseRequisitionRowChanging != null)) {
                    this.dsAccPurchaseRequisitionRowChanging(this, new dsAccPurchaseRequisitionRowChangeEvent(((dsAccPurchaseRequisitionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.dsAccPurchaseRequisitionRowDeleted != null)) {
                    this.dsAccPurchaseRequisitionRowDeleted(this, new dsAccPurchaseRequisitionRowChangeEvent(((dsAccPurchaseRequisitionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.dsAccPurchaseRequisitionRowDeleting != null)) {
                    this.dsAccPurchaseRequisitionRowDeleting(this, new dsAccPurchaseRequisitionRowChangeEvent(((dsAccPurchaseRequisitionRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemovedsAccPurchaseRequisitionRow(dsAccPurchaseRequisitionRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsAccPurchaseRequisition ds = new dsAccPurchaseRequisition();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "dsAccPurchaseRequisitionDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class dsAccPurchaseRequisitionRow : global::System.Data.DataRow {
            
            private dsAccPurchaseRequisitionDataTable tabledsAccPurchaseRequisition;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal dsAccPurchaseRequisitionRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabledsAccPurchaseRequisition = ((dsAccPurchaseRequisitionDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BYR_ACC_GRP_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.BYR_ACC_GRP_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BYR_ACC_GRP_NAME_EN\' in table \'dsAccPurchaseRequisition\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.BYR_ACC_GRP_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string BYR_ACC_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.BYR_ACC_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BYR_ACC_NAME_EN\' in table \'dsAccPurchaseRequisition\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.BYR_ACC_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string STYLE_NO {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.STYLE_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STYLE_NO\' in table \'dsAccPurchaseRequisition\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.STYLE_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string MC_ORDER_NO_LST {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.MC_ORDER_NO_LSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MC_ORDER_NO_LST\' in table \'dsAccPurchaseRequisition\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.MC_ORDER_NO_LSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PURC_REQ_NO {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.PURC_REQ_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PURC_REQ_NO\' in table \'dsAccPurchaseRequisition\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.PURC_REQ_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime PURC_REQ_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabledsAccPurchaseRequisition.PURC_REQ_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PURC_REQ_DT\' in table \'dsAccPurchaseRequisition\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.PURC_REQ_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ITEM_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.ITEM_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ITEM_NAME_EN\' in table \'dsAccPurchaseRequisition\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.ITEM_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string COLOR_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.COLOR_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COLOR_NAME_EN\' in table \'dsAccPurchaseRequisition\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.COLOR_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string SIZE_CODE {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.SIZE_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SIZE_CODE\' in table \'dsAccPurchaseRequisition\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.SIZE_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PROD_COLOR_NAME_EN {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.PROD_COLOR_NAME_ENColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PROD_COLOR_NAME_EN\' in table \'dsAccPurchaseRequisition\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.PROD_COLOR_NAME_ENColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PROD_SIZE_CODE {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.PROD_SIZE_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PROD_SIZE_CODE\' in table \'dsAccPurchaseRequisition\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.PROD_SIZE_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ITEM_SPEC_AUTO {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.ITEM_SPEC_AUTOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ITEM_SPEC_AUTO\' in table \'dsAccPurchaseRequisition\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.ITEM_SPEC_AUTOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ITEM_CODE {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.ITEM_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ITEM_CODE\' in table \'dsAccPurchaseRequisition\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.ITEM_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PARTICULARS {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.PARTICULARSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PARTICULARS\' in table \'dsAccPurchaseRequisition\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.PARTICULARSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal RQD_QTY {
                get {
                    try {
                        return ((decimal)(this[this.tabledsAccPurchaseRequisition.RQD_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RQD_QTY\' in table \'dsAccPurchaseRequisition\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.RQD_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ORDER_QTY {
                get {
                    try {
                        return ((decimal)(this[this.tabledsAccPurchaseRequisition.ORDER_QTYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ORDER_QTY\' in table \'dsAccPurchaseRequisition\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.ORDER_QTYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string MOU_CODE {
                get {
                    try {
                        return ((string)(this[this.tabledsAccPurchaseRequisition.MOU_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MOU_CODE\' in table \'dsAccPurchaseRequisition\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabledsAccPurchaseRequisition.MOU_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBYR_ACC_GRP_NAME_ENNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.BYR_ACC_GRP_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBYR_ACC_GRP_NAME_ENNull() {
                this[this.tabledsAccPurchaseRequisition.BYR_ACC_GRP_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsBYR_ACC_NAME_ENNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.BYR_ACC_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetBYR_ACC_NAME_ENNull() {
                this[this.tabledsAccPurchaseRequisition.BYR_ACC_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSTYLE_NONull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.STYLE_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSTYLE_NONull() {
                this[this.tabledsAccPurchaseRequisition.STYLE_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMC_ORDER_NO_LSTNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.MC_ORDER_NO_LSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMC_ORDER_NO_LSTNull() {
                this[this.tabledsAccPurchaseRequisition.MC_ORDER_NO_LSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPURC_REQ_NONull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.PURC_REQ_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPURC_REQ_NONull() {
                this[this.tabledsAccPurchaseRequisition.PURC_REQ_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPURC_REQ_DTNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.PURC_REQ_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPURC_REQ_DTNull() {
                this[this.tabledsAccPurchaseRequisition.PURC_REQ_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsITEM_NAME_ENNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.ITEM_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetITEM_NAME_ENNull() {
                this[this.tabledsAccPurchaseRequisition.ITEM_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCOLOR_NAME_ENNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.COLOR_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCOLOR_NAME_ENNull() {
                this[this.tabledsAccPurchaseRequisition.COLOR_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSIZE_CODENull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.SIZE_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSIZE_CODENull() {
                this[this.tabledsAccPurchaseRequisition.SIZE_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPROD_COLOR_NAME_ENNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.PROD_COLOR_NAME_ENColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPROD_COLOR_NAME_ENNull() {
                this[this.tabledsAccPurchaseRequisition.PROD_COLOR_NAME_ENColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPROD_SIZE_CODENull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.PROD_SIZE_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPROD_SIZE_CODENull() {
                this[this.tabledsAccPurchaseRequisition.PROD_SIZE_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsITEM_SPEC_AUTONull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.ITEM_SPEC_AUTOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetITEM_SPEC_AUTONull() {
                this[this.tabledsAccPurchaseRequisition.ITEM_SPEC_AUTOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsITEM_CODENull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.ITEM_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetITEM_CODENull() {
                this[this.tabledsAccPurchaseRequisition.ITEM_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPARTICULARSNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.PARTICULARSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPARTICULARSNull() {
                this[this.tabledsAccPurchaseRequisition.PARTICULARSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsRQD_QTYNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.RQD_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetRQD_QTYNull() {
                this[this.tabledsAccPurchaseRequisition.RQD_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsORDER_QTYNull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.ORDER_QTYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetORDER_QTYNull() {
                this[this.tabledsAccPurchaseRequisition.ORDER_QTYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMOU_CODENull() {
                return this.IsNull(this.tabledsAccPurchaseRequisition.MOU_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMOU_CODENull() {
                this[this.tabledsAccPurchaseRequisition.MOU_CODEColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class dsAccPurchaseRequisitionRowChangeEvent : global::System.EventArgs {
            
            private dsAccPurchaseRequisitionRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAccPurchaseRequisitionRowChangeEvent(dsAccPurchaseRequisitionRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public dsAccPurchaseRequisitionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591